// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgucVUXxuK4g7L_UEu8x7zwYIWfdGTQZs',
    appId: '1:75064126974:web:0054da71a94a93230764af',
    messagingSenderId: '75064126974',
    projectId: 'chahanjan-81bce',
    authDomain: 'chahanjan-81bce.firebaseapp.com',
    storageBucket: 'chahanjan-81bce.firebasestorage.app',
    measurementId: 'G-65TTHB52W2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE1KHVqMLIwcAuUbWAxFEt7U2Z4_XmbKQ',
    appId: '1:75064126974:ios:c7603de8a5ec28620764af',
    messagingSenderId: '75064126974',
    projectId: 'chahanjan-81bce',
    storageBucket: 'chahanjan-81bce.firebasestorage.app',
    iosClientId: '75064126974-fo9emd4bjsuf2qleecusqev6ta17d0dk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chahanjanApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE1KHVqMLIwcAuUbWAxFEt7U2Z4_XmbKQ',
    appId: '1:75064126974:ios:c7603de8a5ec28620764af',
    messagingSenderId: '75064126974',
    projectId: 'chahanjan-81bce',
    storageBucket: 'chahanjan-81bce.firebasestorage.app',
    iosClientId: '75064126974-fo9emd4bjsuf2qleecusqev6ta17d0dk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chahanjanApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZl5_1Zc-6gHpPKlkPmooHgBss2b06NzQ',
    appId: '1:75064126974:android:05e5e177aa3b19df0764af',
    messagingSenderId: '75064126974',
    projectId: 'chahanjan-81bce',
    storageBucket: 'chahanjan-81bce.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgucVUXxuK4g7L_UEu8x7zwYIWfdGTQZs',
    appId: '1:75064126974:web:30fb36a3713146d00764af',
    messagingSenderId: '75064126974',
    projectId: 'chahanjan-81bce',
    authDomain: 'chahanjan-81bce.firebaseapp.com',
    storageBucket: 'chahanjan-81bce.firebasestorage.app',
    measurementId: 'G-CB5RSEWPTT',
  );

}